---
framework: mocha
preRun:
  command:
    - yarn install
    - NODE_ENV=production yarn build
preMerge:
  pattern:
    - "test/{commands,tests,src,plugins,models}/*.js"
postMerge:
  pattern:
    - "test/{commands,tests,src,plugins,models}/*.js"
postRun:
  command:
    - yarn --version
configFile: test/.mocharc.yml
version: 1.0
